# /user/
# Get user by company id
GET {{host-url}}//users/1

#Create new user
###
POST {{host-url}}/users
Content-Type: application/json

{
  "email": "test@pl",
  "password": "s3cret",
  "firstName": "RequestName",
  "lastName": "RequestLastName",
  "userType": "Test-User"
}

###
GET {{host-url}}/companies/5
###

GET {{host-url}}/jobs

###
DELETE {{host-url}}/users/delete/1
###

###
POST {{host-url}}/jobs
Content-Type: application/json

{
    "companyId": "1",
    "position": "test position",
    "shortDescription":"simple job 2"
}
###
